#calculating percentage discount
Feature: Discount calculator

  Scenario: Calculate discount as per given amount and condition
    Given I have an amount of 1000
    And I have selected discount type "percentage"
    And The percentage is 10
    When I calculate the discount
    Then The calculated discount and amount should be 100 and 900 respectively

  Scenario: Calculate discount as per given amount and condition
    Given I have an amount of 1000
    And I have selected discount type "flat"
    And The flat discount is 20
    When I calculate the discount
    Then The calculated discount and amount should be 20 and 980 respectively

  Scenario: Calculate discount as per given amount and condition
    Given I have an amount of 1000
    And I have selected discount type "both"
    And The percentage is 10
    And The flat discount is 20
    And I have selected "lower" as applicable type
    When I calculate the discount
    Then The calculated discount and amount should be 20 and 980 respectively

  Scenario Outline: Calculate discount as per given amount and condition
    Given I have an amount of <amount>
    And I have selected discount type "<discount_type>"
    And The percentage is <percentage>
    And The flat discount is <flat_discount>
    And I have selected "<applicable_type>" as applicable type
    When I calculate the discount
    Then The calculated discount and amount should be <discount_amount> and <calculated_amount> respectively

    Examples:
      | amount | discount_type | percentage | flat_discount | applicable_type | discount_amount | calculated_amount |
      | 1000   | percentage    | 10         | 0             | null            | 100             | 900               |
      | 1000   | flat          | 0          | 80            | null            | 80              | 920               |
      | 1000   | both          | 10         | 30            | lower           | 30              | 970               |
      | 1000   | both          | 10         | 25            | higher          | 100             | 900               |
      | 1000   | both          | 10         | 25            | combination     | 125             | 875               |

  #testing every possible combination
  Scenario Outline: Calculate discount as per given amount and condition
    Given I have an amount of <amount>
    And I have selected discount type "<discount_type>"
    And The percentage is <percentage>
    And The flat discount is <flat_discount>
    And I have selected "<applicable_type>" as applicable type
    And I have given per user discount <per_user_discount>
    And And per user discount taken is <per_user_discount_taken>
    And I have given per user per merchant discount <per_user_per_merchant>
    And And per user per merchant discount taken is <per_user_per_merchant_discount_taken>
    And I have given per user per day discount <per_user_per_day>
    And And per user per day discount taken is <per_user_per_day_discount_taken>
    And I have given per user per month discount <per_user_per_month>
    And And per user per month discount taken is <per_user_per_month_discount_taken>
    And I have given per merchant per day discount <per_merchant_per_day>
    And And per merchant per day discount taken is <per_merchant_per_day_discount_taken>
    And I have given per merchant per month discount <per_merchant_per_month>
    And And per merchant per month discount taken is <per_merchant_per_month_discount_taken>
    When I calculate the discount
    Then The calculated discount and amount should be <discount_amount> and <calculated_amount> respectively

    Examples:
      | amount | discount_type | percentage | flat_discount | applicable_type | per_user_discount | per_user_discount_taken | per_user_per_merchant | per_user_per_merchant_discount_taken | per_user_per_day | per_user_per_day_discount_taken | per_user_per_month | per_user_per_month_discount_taken | per_merchant_per_day | per_merchant_per_day_discount_taken | per_merchant_per_month | per_merchant_per_month_discount_taken | discount_amount | calculated_amount |
      | 1000   | both          | 10         | 50            | combination     | 200               | 10                      | 190                   | 10                                   | 180              | 10                              | 170                | 40                                | 140                  | 0                                   | 150                    | 10                                    | 130             | 870               |
      | 1000   | both          | 10         | 50            | combination     | 200               | 200                     | 190                   | 190                                  | 180              | 180                             | 170                | 170                               | 140                  | 140                                 | 150                    | 150                                   | 0               | 1000              |
      #DEFAULT SETUP
      | 1000   | percentage    | 10         | 0             | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 100             | 900               |
      | 1000   | flat          | 0          | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 20              | 980               |
      | 1000   | both          | 10         | 20            | lower           | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 20              | 980               |
      | 1000   | both          | 10         | 20            | higher          | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 100             | 900               |
      | 1000   | both          | 10         | 20            | combination     | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 120             | 880               |
      #CONFIGURATION SETUP ENABLED
      | 1000   | percentage    | 10         | 0             | null            | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      | 1000   | flat          | 0          | 20            | null            | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 20            | lower           | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 20            | higher          | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 20            | combination     | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      #DAILY LIMIT ENABLED
      | 1000   | percentage    | 10         | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 6               | 994               |
      | 1000   | flat          | 0          | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 6               | 994               |
      | 1000   | both          | 10         | 20            | higher          | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 6               | 994               |
      | 1000   | both          | 10         | 20            | lower           | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 6               | 994               |
      | 1000   | both          | 10         | 20            | combination     | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 6               | 994               |
      #CONFIGURATION SETUP AND DAILY LIMIT ENABLED
      | 1000   | percentage    | 10         | 0             | null            | 50                | 40                      | 25                    | 20                                   | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 5               | 995               |
      | 1000   | flat          | 0          | 20            | null            | 50                | 40                      | 25                    | 20                                   | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 20            | lower           | 50                | 40                      | 25                    | 20                                   | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 20            | higher          | 50                | 40                      | 25                    | 20                                   | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 20            | combination     | 50                | 40                      | 25                    | 20                                   | 10               | 4                               | 0                  | 0                                 | 50                   | 40                                  | 0                      | 0                                     | 5               | 995               |
      #MONTHLY LIMIT ONLY ENABLED
      | 1000   | percentage    | 10         | 0             | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 100             | 900               |
      | 1000   | flat          | 0          | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 20              | 980               |
      | 1000   | both          | 10         | 20            | lower           | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 20              | 980               |
      | 1000   | both          | 10         | 20            | higher          | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 100             | 900               |
      | 1000   | both          | 10         | 20            | combination     | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 120             | 880               |
      #CONFIGURATION SETUP AND MONTHLY LIMIT ENABLED
      | 1000   | percentage    | 10         | 20            | null            | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | flat          | 10         | 20            | null            | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | both          | 10         | 20            | lower           | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | both          | 10         | 20            | higher          | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | both          | 10         | 20            | combination     | 50                | 20                      | 25                    | 20                                   | 0                | 0                               | 1000               | 700                               | 0                    | 0                                   | 5000                   | 4500                                  | 5               | 995               |
      #DAILY LIMIT AND MONTHLY LIMIT ENABLED
      | 1000   | percentage    | 10         | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 6               | 994               |
      | 1000   | flat          | 10         | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 6               | 994               |
      | 1000   | both          | 10         | 20            | lower           | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 6               | 994               |
      | 1000   | both          | 10         | 20            | higher          | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 6               | 994               |
      | 1000   | both          | 10         | 20            | combination     | 0                 | 0                       | 0                     | 0                                    | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 6               | 994               |
      #CONFIGURATION SETUP AND MONTHLY LIMIT AND DAILY LIMIT ENABLED
      | 1000   | percentage    | 10         | 0             | null            | 50                | 20                      | 25                    | 20                                   | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | flat          | 0          | 20            | null            | 50                | 20                      | 25                    | 20                                   | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | both          | 10         | 20            | lower           | 50                | 20                      | 25                    | 20                                   | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | both          | 10         | 20            | higher          | 50                | 20                      | 25                    | 20                                   | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 5               | 995               |
      | 1000   | both          | 10         | 20            | combination     | 50                | 20                      | 25                    | 20                                   | 10               | 4                               | 1000               | 700                               | 50                   | 40                                  | 5000                   | 4500                                  | 5               | 995               |

      | 1000   | flat          | 0          | 20            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 20              | 980               |
      | 1000   | percentage    | 10         | 0             | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 100             | 900               |
      | 1000   | both          | 10         | 20            | lower           | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 20              | 980               |
      | 1000   | both          | 10         | 20            | higher          | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 100             | 900               |
      | 1000   | both          | 10         | 20            | combination     | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 120             | 880               |
      | 1000   | flat          | 0          | 20            | null            | 20                | 10                      | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 10              | 990               |
      | 1000   | percentage    | 10         | 0             | null            | 20                | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 20              | 980               |
      | 1000   | both          | 10         | 20            | lower           | 10                | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 10              | 990               |
      | 1000   | both          | 10         | 20            | higher          | 50                | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 50              | 950               |
      | 1000   | both          | 10         | 20            | combination     | 60                | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 60              | 940               |
      | 1000   | flat          | 10         | 20            | null            | 0                 | 0                       | 10                    | 5                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      | 1000   | percentage    | 10         | 20            | null            | 0                 | 0                       | 10                    | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 10              | 990               |
      | 1000   | both          | 10         | 5             | lower           | 0                 | 0                       | 10                    | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 5               | 995               |
      | 1000   | both          | 10         | 5             | higher          | 0                 | 0                       | 120                   | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 100             | 900               |
      | 1000   | both          | 10         | 5             | combination     | 0                 | 0                       | 100                   | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 100             | 900               |
      | 1000   | flat          | 10         | 5             | null            | 0                 | 0                       | 0                     | 0                                    | 10               | 9                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | percentage    | 10         | 50            | null            | 0                 | 0                       | 0                     | 0                                    | 40               | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 40              | 960               |
      | 1000   | both          | 10         | 50            | lower           | 0                 | 0                       | 0                     | 0                                    | 40               | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 40              | 960               |
      | 1000   | both          | 10         | 50            | higher          | 0                 | 0                       | 0                     | 0                                    | 40               | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 40              | 960               |
      | 1000   | both          | 10         | 50            | combination     | 0                 | 0                       | 0                     | 0                                    | 40               | 0                               | 0                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 40              | 960               |
      | 1000   | flat          | 10         | 5             | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1                  | 1                                 | 0                    | 0                                   | 0                      | 0                                     | 0               | 1000              |
      | 1000   | percentage    | 10         | 50            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | lower           | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | higher          | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | combination     | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 1                  | 0                                 | 0                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | flat          | 10         | 50            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 1                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | percentage    | 10         | 50            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 1                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | lower           | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 1                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | higher          | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 1                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | combination     | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 1                    | 0                                   | 0                      | 0                                     | 1               | 999               |
      | 1000   | flat          | 10         | 50            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 1                      | 0                                     | 1               | 999               |
      | 1000   | percentage    | 10         | 50            | null            | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 1                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | lower           | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 1                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | higher          | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 1                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | combination     | 0                 | 0                       | 0                     | 0                                    | 0                | 0                               | 0                  | 0                                 | 0                    | 0                                   | 1                      | 0                                     | 1               | 999               |
      | 1000   | both          | 10         | 50            | combination     | 40                | 5                       | 40                    | 10                                   | 40               | 0                               | 40                 | 15                                | 30                   | 6                                   | 30                     | 7                                     | 23              | 977               |
